site: Shawn Zhou
url: https://shawnyzhou.com
title: 
description: 

author:
  name: Shawn Zhou
  url: https://shawnyzhou.com

permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  writings:
    output: true
