site: Shawn Zhou
url: https://shawnyzhou.com
title: Shawn Zhou
description: Design, architecture, real estate, systems, and writing by Shawn Zhou

author:
  name: Shawn Zhou
  url: https://shawnyzhou.com

permalink: pretty

baseurl: ""

lang: en
timezone: America/Los_Angeles

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  essays:
    output: true
    permalink: /essays/:title/
  journals:
    output: true
    permalink: /journals/:title/
