site: shawnyzhou
url: https://shawnyzhou.com
title: shawnyzhou
description: Shawn Zhou's personal website

twitter:
  username: 
  card: summary
  creator: 

author:
  name: Shawn Zhou
  avatar:
  email: sz@shawnyzhou.com
  url: https://shawnyzhou.com

permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
